### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tasaduq** [miloszw/pocket-stats#1]
After having installed the packed.

![image](https://user-images.githubusercontent.com/9743841/56075121-d5088280-5dd6-11e9-89aa-7243ff2ca011.png)

it doesn't do anything

![image](https://user-images.githubusercontent.com/9743841/56075126-e0f44480-5dd6-11e9-82cf-c9c3e99eac37.png)

is there something I am not doing right?

**Comment by mwielondek** [comment]
Yes you're right, that won't work. I've made a typo in the docs. It should read `node app.js`. Thanks!
